### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by kengkeng1** [liuyyy111/Point-RAE#2]
I meet the error when I run the Stage I code:

Traceback (most recent call last):
  File "main_autoencoder.py", line 72, in <module>
    main()
  File "main_autoencoder.py", line 68, in main
    run_net(args, config, train_writer, val_writer)
  File "/hy-tmp/Point-RAE-main/tools/runner_autoencoder.py", line 96, in run_net
    optimizer, scheduler = builder.build_opti_sche(base_model, config)
  File "/hy-tmp/Point-RAE-main/tools/builder.py", line 103, in build_opti_sche
    assigner = LayerDecayValueAssigner(list(0.65 ** (config.model.depth + 1 - i) for i in range(config.model.depth + 2)))
AttributeError: 'EasyDict' object has no attribute 'depth'

It seems that there is not exist the "depth" in the "Point-RAE-main/cfgs/autoencoder/act_dvae_with_pretrained_transformer.yaml".

**Comment by liuyyy111** [comment]
My apologies, the code was dispatched in a rush and I didn't have the opportunity to conduct a proper review before uploading. I will prioritize a comprehensive check shortly. Thank you for your patience and comprehension.

**Comment by kengkeng1** [comment]
Thank you for your reply.

**Comment by kengkeng1** [comment]
When will the code be update？
